baseURL = "https://liuwenzhuzzz.xyz/" # 博客地址
languageCode = "zh-CN" # 语言
title = "LiUWENZHUzzZ" # 标题
hasCJKLanguage = true # 开启可以让「字数统计」统计汉字
theme = "LeaveIt" # 主题

paginate = 10 # 每页的文章数
enableEmoji = true # 支持 Emoji
enableRobotsTXT = true # 支持 robots.txt
googleAnalytics = "" # Google 统计 id

preserveTaxonomyNames = true

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

[params]
    since = 2019
    author = "LiUWENZHUzzZ"                    # Author's name
    avatar = "https://i.loli.net/2019/07/31/5d419cb863c1219201.jpg"                                                    # Author's avatar
    subtitle = "Pursuit comes from love"       # Subtitle
    cdn_url = ""                               # Base CDN URL
    home_mode = ""                             # post or other
    enableGitalk = true                        # gitalk 评论系统

    google_verification = ""

    description = ""                           # (Meta) 描述
    keywords = ""                              # site keywords

    beian = ""
    baiduAnalytics = ""

    license= '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'

[params.social]
    GitHub = "LiUWENZHUzzZ"
    Twitter = "LiUWENZHUzzZ"
    Email   = "liuwenzhuzzz@gmail.com"
    #Wechat = "/images/me/wechat.jpg"  # Wechat QRcode image
	Weibo = "https://weibo.com/u/7245988988"
    Cloudmusic = "http://music.163.com/m/user/home?id=291859070"
    Coolapk = "http://www.coolapk.com/u/2806249"
    Bilibili = "https://space.bilibili.com/253204549?share_medium=android&share_source=copy_link&bbid=XY00CC30A9753C75808FACACA40CCCA888BDE&ts=1564752862468"
    #Alipay = "/images/me/alipay.jpg"
    #Jianshu = "https://www.jianshu.com/u/2f589e9a878b"

[params.gitalk] # Github: https://github.com/gitalk/gitalk
    clientID = "" # Your client ID
    clientSecret = "" # Your client secret
    repo = "" # The repo to store comments
    owner = "" # Your GitHub ID
    admin= "" # Required. Github repository owner and collaborators. (Users who having write access to this repository)
    id= "location.pathname" # The unique id of the page.
    labels= "gitalk" # Github issue labels. If you used to use Gitment, you can change it
    perPage= 15 # Pagination size, with maximum 100.
    pagerDirection= "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually= false # If it is 'false', it is auto to make a Github issue when the administrators login.
    distractionFreeMode= false # Enable hot key (cmd|ctrl + enter) submit comment.
